apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dgbg5y5vn-python
  janus-idp.io/tekton: dgbg5y5vn-python
  backstage.io/kubernetes-id: dgbg5y5vn-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: dgbg5y5vn-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
